### ISSUE TITLE
CSS:SVG is invalid folder name in windows.

### ISSUE THREAD

**Issue by sanchit94** [edgarordonez/books#2]
When trying to clone this repository and checkout at branch **master**, I'm getting an error in windows 10:
`fatal: cannot create directory at 'CSS:SVG': Invalid argument`

I think changing the folder name might fix this issue.

**Comment by edgarordonez** [comment]
Hi @sanchit94 

I just fixed it, thanks! :)

**Comment by sanchit94** [comment]
Great! And thanks for the books, they are valuable resources for learners!
